"""v3

Revision ID: 11f306171410
Revises: 50e41f8b6c22
Create Date: 2022-03-27 03:05:08.640293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f306171410'
down_revision = '50e41f8b6c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('code', sa.String(length=4), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'code')
    # ### end Alembic commands ###
